name: PR title

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  title:
    name: PR title
    uses: FerrLabs/.github/.github/workflows/reusable-pr-title.yml@b6a08e6055076c18cfa7b8f80c9925275ed407fe # main
