name: PR title

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  title:
    name: PR title
    uses: FerrLabs/.github/.github/workflows/reusable-pr-title.yml@f9fac3f7da330dd0136172ac5435f3cfccb809a7 # main
