name: PR title

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  title:
    name: PR title
    uses: FerrLabs/.github/.github/workflows/reusable-pr-title.yml@88f0161ac0567a4cd82906562d44674dbb89ae67 # main
