name: Renovate rebase now

on:
  pull_request:
    types: [edited]

jobs:
  dispatch:
    uses: FerrLabs/.github/.github/workflows/reusable-renovate-dispatch.yml@e186f50feddaca3b371082879a96bdd34d33bb91 # main
    secrets: inherit
