name: Renovate rebase now

on:
  pull_request:
    types: [edited]

jobs:
  dispatch:
    uses: FerrLabs/.github/.github/workflows/reusable-renovate-dispatch.yml@a5886d74297dafc6aed9ee9f9aa75d7a06c831ca # main
    secrets: inherit
