name: Renovate rebase now

on:
  pull_request:
    types: [edited]

jobs:
  dispatch:
    uses: FerrLabs/.github/.github/workflows/reusable-renovate-dispatch.yml@5cbbf0fc748727ecc99bfa4596d8c59a163c7267 # main
    secrets: inherit
