name: SonarQube

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    name: SonarQube analysis
    permissions:
      contents: read
      pull-requests: write
    uses: FerrLabs/.github/.github/workflows/reusable-sonarqube-scan.yml@b959064c9d271bf841ea67f445e41ee1d2e68d8d # main
    with:
      project-key: UI
    secrets: inherit
