name: SonarQube

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    name: SonarQube analysis
    permissions:
      contents: read
      pull-requests: write
    uses: FerrLabs/.github/.github/workflows/reusable-sonarqube-scan.yml@c4121e79b9e15551efce374b7e9f4990667b9a36 # main
    with:
      project-key: UI
    secrets: inherit
