name: SonarQube

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    name: SonarQube analysis
    permissions:
      contents: read
      pull-requests: write
    uses: FerrLabs/.github/.github/workflows/reusable-sonarqube-scan.yml@dc37316d0b31cb7a47455f2933202533f9c909bd # main
    with:
      project-key: UI
    secrets: inherit
