name: Storybook image

on:
  push:
    branches: [main]
    paths:
      - 'packages/showcase/**'
      - 'packages/ui-ng/**'
      - 'packages/foundation/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/storybook-image.yml'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build & Push Storybook
    runs-on: ${{ github.event.repository.private && 'ferrlabs-k8s-large' || 'ubuntu-latest' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Build and push
        run: |
          SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          BUILD="${{ github.run_number }}"
          IMAGE=ghcr.io/ferrlabs/ui/showcase
          buildah login -u ${{ github.actor }} -p ${GITHUB_TOKEN} ghcr.io
          buildah build --isolation=chroot \
            -t ${IMAGE}:build-${BUILD} \
            -f packages/showcase/Dockerfile .
          buildah tag ${IMAGE}:build-${BUILD} ${IMAGE}:main-${SHA}
          buildah tag ${IMAGE}:build-${BUILD} ${IMAGE}:latest
          buildah push ${IMAGE}:build-${BUILD}
          buildah push ${IMAGE}:main-${SHA}
          buildah push ${IMAGE}:latest
